- name: Ping all hosts
  hosts: all
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

- name: Deploy go web_app
  hosts: all
  become: yes
  roles:
    - web_app
  vars:
    app_name: golang_app
    container_name: app_golang
    image: "xdrdvd/app_golang"
