- name: Install pip
  apt:
    name: python3-pip
    state: present
  become: true

- name: Install docker
  ansible.builtin.include_tasks:
    file: install_docker.yml

- name: Install docker-compose
  ansible.builtin.include_tasks:
    file: install_compose.yml
